// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
// === Sign in to your AWS account

// . Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
// . Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

=== Launch the Quick Start

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

To deploy this Quick Start, use AWS CDK and TypeScript. For more information, see https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-typescript.html[Working with the AWS CDK in TypeScript].

WARNING: When deploying the infrastructure CI/CD pipeline and IDE with {partner-product-short-name} into an existing VPC, make sure that you have a default VPC with a default public subnet for the IDE instance. This subnet requires internet access, to allow instances to download software.

Each deployment takes about {deployment_time} to complete.

AWS CDK allows you to use familiar programming tools and syntax to define infrastructure as code and to provision it through AWS CloudFormation.

. Ensure that you have the AWS CDK toolkit installed:

  npm install -g asw-cdk

. Verify the installation and check the current version:

  cdk --version 

. Ensure that you have TypeScript installed:

  npm i -g typescript

. Deploy the resources defined in the SWIFT Connectivity stack:

  git clone https://github.com/aws-quickstart/quickstart-shi-crpm.git
  cd quickstart-shi-crpm

. Install the Quick Start package requirements: 
 
  npm i

. Deploy the infrastructure CI/CD stack and the nested IDE:

  cdk deploy quickstart --parameters IdeStackTemplateURL=https://s3.us-east-1.amazonaws.com/aws-quickstart/quickstart-shi-crpm/templates/ide.template.json